config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
   root to: 'landing#index'
   get :about, to: 'static_pages#about'
   post :upvote, to: 'votes#upvote'
   post :downvote, to: 'votes#downvote'
   resources :topics  do
     resources :posts, except: [:show] do
       resources :comments
     end
   end

   resources :users, only: [:new, :edit, :create, :update]
   resources :sessions, only: [:new, :create, :destroy]
   resources :password_resets, only: [:new, :create, :edit, :update]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  # mount_uploader :image, ImageUploader
  belongs_to :post
  belongs_to :user
  paginates_per 4
  has_many :votes
  validates :body, length: {minimum: 2}, presence: true

  def total_votes
    votes.pluck(:value).sum
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  respond_to :js
  before_action :authenticate!, only: [:create, :edit, :update, :new, :destroy]

  def index
    @post = Post.includes(:comments).friendly.find(params[:post_id])
    @comments = @post.comments.order(created_at: :desc).page params[:page]
    @topic = Topic.friendly.find(params[:topic_id])
    @comment = Comment.new
  end

  def create
    @topic = Topic.friendly.find(params[:topic_id])
    @post = Post.friendly.find(params[:post_id])
    @comment = current_user.comments.build(comment_params.merge(post_id: @post.id))
    @new_comment = Comment.new

    if @comment.save
      CommentBroadcastJob.perform_later("create", @comment)
      flash.now[:success] = "You've created a new comment"
    else
      flash.now[:danger] = @comment.errors.full_messages
    end
  end

  def edit
    @comment = Comment.find_by(id: params[:id])
    @post = @comment.post
    @topic = @post.topic
    authorize @comment
  end

  def update
    @comment = Comment.find_by(id: params[:id])
    @post = @comment.post
    @topic = @post.topic
    authorize @comment

    if @comment.update(comment_params)
      CommentBroadcastJob.perform_later("update", @comment)
      flash.now[:success] = "You've updated your comment"
    else
      flash.now[:danger] = @comment.errors.full_messages
    end
  end

  def destroy
    @comment = Comment.find_by(id: params[:id])

    authorize @comment

    if @comment.destroy
      CommentBroadcastJob.perform_now("destroy", @comment)
      flash.now[:danger] = "Comment Deleted!"
    end

  end

  private

    def comment_params
      params.require(:comment).permit(:body, :image)
    end
end

app/views/comments/_comment.html.erb
<div id="comment-form-holder-<%=comment.id%>" class="comment" data-id="<%= comment.id %>">
    <div class="comment-child">
        <%=comment.body%>
        <div class="comment-button-container">
          <div class="comment-button align">
            <% if comment.user == current_user %>
            <%=link_to "Edit", edit_topic_post_comment_path(topic, post, comment), remote: true, class: 'btn btn-info'%>
            <%end%>
            <% if comment.user == current_user || current_user&.admin? || current_user&.moderator? %>
            <%=link_to "Delete", topic_post_comment_path(topic, post, comment), remote: true, method: :delete, data: {Confirm: "Delete?"}, class:'btn btn-danger'%>
            <%end%>
          </div>
        </div>
        <div class="comment-vote-container align">
          <div class="comment-vote inline">
            <%= link_to "Upvote", upvote_path(comment_id: comment.id), method: :post, remote: true%>
            <%= link_to "Downvote", downvote_path(comment_id: comment.id), method: :post, remote: true%>
          </div>
            <div class="comment-total-votes inline">
              <%=comment.total_votes%>
            </div>
        </div>
    </div>
</div>

app/views/comments/_edit.html.erb
<div class="form-container" id="comment-update">
    <%= form_for(comment, url: topic_post_comment_path(topic, post, comment), remote: true ,html: { id: "comment-update-form" }) do |f| %>

    <div class="form-group">
      <h4> <%= f.label :text_field, "Body", class:"form-text" %> </h4>
      <%= f.text_field :body, id: "comment_body_field", class: 'form-control ' %>
    </div>

    <div class="form-group text-center">
      <div class="btn btn-success btn-lg cancel-button">
        Cancel
      </div>
      <%= f.submit "Update Comment", class: "btn btn-success btn-lg" %>
    </div>

    <% end %>
</div>

app/views/comments/_form.html.erb
<div class="comment-create-form">
  <%= form_for(comment, url: topic_post_comments_path(post.topic, post), remote: true, html: { id: "comment-create-form" }) do |f| %>
  <h1 class="text-center">
    Create Comment
  </h1>

  <div class="form-group" >
    <h4 >
      <%= f.label :text_field, "Body" %>
    </h4>
    <%= f.text_field :body, id: "comment_body_field", class: 'form-control' %>
  </div>

  <div class="form-group text-center">
    <%= f.submit "Create Comment", class: "btn btn-success btn-lg" %>
  </div>
  <% end %>
</div>

app/views/comments/create.js.erb
  $('#flash-messages-container').html("<%=j render partial: 'partials/flash_messages' %>")

  <% if @comment.persisted? %>

    $('.form-container').html("<%=j render partial: 'form', locals: { comment: @new_comment, post: @post, topic: @topic } %>")
  <% end %>

app/views/comments/destroy.js.erb
$('#flash-messages-container').html("<%=j render partial: 'partials/flash_messages' %>")

$('#comment-form-holder-<%=@comment.id%>').remove()

app/views/comments/edit.html.erb
<div class="form-container">

    <%= form_for(@comment, url: topic_post_comment_path(@topic, @post, @comment), html: { id: "comment-update-form" }) do |f| %>
    <h1 class="text-center">
      Update Comment
    </h1>
    <div class="form-button">      
      <button><%=link_to "Back to Posts", topic_posts_path(@topic)%></button>
    </div>
    <div class="form-group">
      <h4> <%= f.label :text_field, "Body", class:"form-text" %> </h4>
      <%= f.text_field :body, id: "comment_body_field", class: 'form-control ' %>
    </div>

    <div class="form-group text-center">
      <%= f.submit "Update Comment", class: "btn btn-success btn-lg" %>
    </div>

    <% end %>
  </div>

app/views/comments/edit.js.erb
$('#comment-form-holder-<%=@comment.id%>').html("<%=j render partial: 'edit', locals: { comment: @comment, post: @post , topic: @topic  } %>")

$('.cancel-button').on('click', function() {
  $('#comment-update').replaceWith("<%=j render partial: 'comment', locals: { comment: @comment, post: @post, topic: @topic }%>")
})

app/views/comments/index.html.erb
<div class="comment-container text-center", data-id="<%= @post.id %>">
    <h1>Comments</h1>
    <%=link_to "Back to Posts", topic_posts_path, class: 'btn btn-primary' %>

    <div class="comment-parent" id="comments">
        <% @comments.each do |comment| %>
          <%= render partial: "comment", locals: { comment: comment, post: @post, topic: @topic } %>
        <%end%>
    </div>

    <%=paginate @comments%>

    <div class="form-container">
        <%= render partial: "form", locals: { comment: @comment, post: @post } %>
    </div>
</div>

app/views/comments/update.js.erb
$('#flash-messages-container').html("<%=j render partial: 'partials/flash_messages' %>")

$('#comment-form-holder-<%=@comment.id%>').html("<%=j render partial: 'comment', locals: { comment: @comment, post: @post, topic: @topic } %>")