config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
   root to: 'landing#index'
   get :about, to: 'static_pages#about'
   post :upvote, to: 'votes#upvote'
   post :downvote, to: 'votes#downvote'
   resources :topics  do
     resources :posts, except: [:show] do
       resources :comments
     end
   end

   resources :users, only: [:new, :edit, :create, :update]
   resources :sessions, only: [:new, :create, :destroy]
   resources :password_resets, only: [:new, :create, :edit, :update]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/topic.rb
class Topic < ApplicationRecord
  extend FriendlyId
  friendly_id :title, :use => :slugged
  paginates_per 2
  belongs_to :user
  has_many :posts

  validates :title, length: { minimum: 3 }, presence: true
  validates :description, length: { minimum: 10 }, presence: true

  before_save :update_slug

  private

  def update_slug
    if title
      self.slug = title.gsub(" ", "-")
    end
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  respond_to :js
  before_action :authenticate!, only: [:create, :edit, :update, :new, :destroy]

  def index
    @topics = Topic.all.page params[:page]

  end

  def new
    @topic = Topic.new
    authorize @topic
  end

  def create
    @topic = current_user.topics.build(topic_params)
    authorize @topic

      if @topic.save
        flash[:success] = "You've created a new topic."
        redirect_to topics_path
      else
        flash[:danger] = @topic.errors.full_messages
        redirect_to new_topic_path
      end
  end

  def edit
    @topic = Topic.friendly.find(params[:id])
    authorize @topic
  end

  def update
    @topic = Topic.friendly.find(params[:id])
    authorize @topic
      if @topic.update(topic_params)
        flash.now[:success] = "Topic Updated!"
      end
  end

  def destroy
    @topic = Topic.friendly.find(params[:id])
    authorize @topic

      if @topic.destroy
        flash.now[:danger] = "Topic Deleted!"

      end
  end


  private

  def topic_params
    params.require(:topic).permit(:title, :description)
  end

end

app/views/topics/_edit.html.erb
<div class="topic-form-update">
  <%= form_for(topic, url: topic_path(topic),remote: true, html: { id: "topic-update-form" }) do |f| %>
  <h1 class="text-center">
    Update Topic
  </h1>

  <div class="form-group">
    <h4> <%= f.label :title_field, "Title" %> </h4>
    <%= f.text_field :title, required: true, id: "topic_title_field", class: 'form-control' %>
  </div>

  <div class="form-group">
    <h4> <%= f.label :text_field, "Description" %> </h4>
    <%= f.text_field :description, id: "topic_description_field", class: 'form-control' %>
  </div>

  <div class="form-group text-center">
    <div class="cancel-button btn btn-success btn-lg">
      Cancel
    </div>
    <%= f.submit "Update Topic", class: "btn btn-success btn-lg" %>
  </div>
  <% end %>
</div>

app/views/topics/_topic.html.erb
<div class="topic-form-holder" data-id="<%=topic.id%>">
    <div class="topic-title">
        <%= link_to topic.title, topic_posts_path(topic) %>
    </div>
    <div class="topic-description">
        <%= topic.description%>
    </div>
    <div class="buttonbar">
        <div class="topic-button">
            <%=link_to "Edit", edit_topic_path(topic), class: 'btn btn-info', remote: true %>
            <%=link_to "Delete", topic_path(topic),remote: true, method: :delete, data: {Confirm: "Delete?"}, class: 'btn btn-danger'%>
        </div>
        <%=link_to "Posted by #{topic.user.username} at #{topic.created_at}", root_path, class: 'topic-detail' %>
    </div>
</div>

app/views/topics/edit.html.erb
<%= form_for(@topic, url: topic_path(@topic), html: { id: "topic-update-form" }) do |f| %>
  <h1 class="text-center">
    Update Topic
  </h1>

  <div class="form-group">
    <h4> <%= f.label :title_field, "Title" %> </h4>
    <%= f.text_field :title, required: true, id: "topic_title_field", class: 'form-control' %>
  </div>

  <div class="form-group">
    <h4> <%= f.label :text_field, "Description" %> </h4>
    <%= f.text_field :description, id: "topic_description_field", class: 'form-control' %>
  </div>

  <div class="form-group text-center">
    <%= f.submit "Update Topic", class: "btn btn-success btn-lg" %>
  </div>
<% end %>

app/views/topics/edit.js.erb
$(".topic-form-holder[data-id=<%=@topic.id%>]").html("<%=j render partial: 'edit', locals: {topic: @topic} %>")

$('.cancel-button').on('click',function(){
  $(".topic-form-holder[data-id=<%=@topic.id%>]").replaceWith("<%=j render partial: 'topic', locals: {topic: @topic} %>")
})

app/views/topics/index.html.erb
<div class="topic text-center">
    <h1>Topics</h1>
    <%= link_to "Add New Topic", new_topic_path, class: 'btn btn-primary' %>
</div>

<div class="topic-container text-center">
    <% @topics.each do |topic| %>
    <%= render partial: "topic", locals: {topic: topic } %>
    <%end%>
</div>

<div class="paginate text-center">
    <%= paginate @topics%>
</div>

app/views/topics/new.html.erb
<%= form_for(@topic, url: topics_path, html: { id: "topic-create-form" }) do |f| %>
  <h1 class=" form-header text-center">
    Create Topic
  </h1>

  <div class="form-group">
    <h4> <%= f.label :title_field, "Title" %> </h4>
    <%= f.text_field :title, required: true, id: "topic_title_field", class: 'form-control' %>
  </div>

  <div class="form-group">
    <h4> <%= f.label :text_field, "Description" %> </h4>
    <%= f.text_field :description, id: "topic_description_field", class: 'form-control' %>
  </div>

  <div class="form-group text-center">
    <%= f.submit "Create Topic", class: "btn btn-success btn-lg" %>
  </div>
<% end %>

app/views/topics/update.js.erb
$('#flash-messages-container').html("<%=j render partial: 'partials/flash_messages' %>")

$(".topic-form-holder[data-id=<%=@topic.id%>]").replaceWith("<%=j render partial: 'topic', locals: {topic: @topic } %>")