config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
   root to: 'landing#index'
   get :about, to: 'static_pages#about'
   post :upvote, to: 'votes#upvote'
   post :downvote, to: 'votes#downvote'
   resources :topics  do
     resources :posts, except: [:show] do
       resources :comments
     end
   end

   resources :users, only: [:new, :edit, :create, :update]
   resources :sessions, only: [:new, :create, :destroy]
   resources :password_resets, only: [:new, :create, :edit, :update]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  extend FriendlyId
  friendly_id :username, :use => :slugged
  mount_uploader :image, ImageUploader
  has_secure_password
  has_many :topics
  has_many :posts
  has_many :comments
  has_many :votes

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, presence: true, uniqueness: true, format: {with: VALID_EMAIL_REGEX}
  validates :username, presence: true, uniqueness: true

  enum role: [:user, :moderator, :admin]

  before_save :update_slug

  private

  def update_slug
    if username
      self.slug = username.gsub(" ", "-")
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  respond_to :js
  before_action :authenticate!, only: [:edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = "You have successfully registered!"
    else
      flash[:danger] = @user.errors.full_messages
    end
  
    redirect_to root_path
  end

  def edit
    @user = User.friendly.find(params[:id])
    authorize @user
  end

  def update
    @user = User.friendly.find(params[:id])
    authorize @user

    if @user.update(user_params)
      flash[:success] = "You've updated your details"
    else
      flash[:danger] = @user.errors.full_messages
    end
      redirect_to edit_user_path(@user)
  end

  private

  def user_params
    params.require(:user).permit(:email, :username, :password, :password_confirmation, :image)
  end

end

app/views/users/_new_session.html.erb
<div class="modal fade" id="modallogin" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">Login</h4>
            </div>
            <div class="modal-body">
                <%= form_tag sessions_path do %>

                <div class="form-group">
                    <h4><%= label_tag "Email", nil, class: 'form-text' %></h4>
                    <%= text_field_tag :email, params[:email], :placeholder => "Enter Email Address", required: true, id: "user_email_field", class: 'form-control' %>
                </div>

                <div class="form-group">
                    <h4><%= label_tag "Password",nil, class: "form-text" %></h4>
                    <%= password_field_tag :password, nil, id: "user_password_field", :placeholder => "Enter password", required: true, class:
            'form-control' %>
                </div>

                <div class="form-group text-center">
                    <%= link_to "First time login?", new_user_path %>
                    <%= link_to "Forget Password?", new_password_reset_path%>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <input type="submit" name="commit" value="Log in" class="btn btn-primary btn-lg" data-disable-with="Log in">
                </div>
                <% end %>

            </div>
        </div>
    </div>
</div>

app/views/users/_new_user.html.erb
<div class="modal fade" id="modalregister" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">Register As New User</h4>
            </div>
            <div class="modal-body">
                <div class="form-container">
                    <%= form_for(:user, url: users_path, html: { id: "user-create-form" }) do |f| %>
                    <div class="form-group">
                        <h4><%=f.label :image, "Profile Picture", class: "form-text"%></h4>

                        <div id="preview-image">
                          <%=image_tag "", class: 'input-img'%>
                        </div>

                        <div class="preview-cancel btn-link">
                          Cancel
                        </div>

                        <%= f.file_field :image, id: "user_image_field", class: 'form-control image-uploader user-image-field' %>

                        <h4>
                            <%= f.label :email_field, "Email", class: "form-text" %>
                        </h4>
                        <%= f.text_field :email, required: true, id: "user_email_field", class: 'form-control' %>

                        <h4>
                            <%= f.label :password, class: "form-text" %>
                        </h4>
                        <%= f.password_field :password, required: true, id: "user_password_field", class: 'form-control' %>

                        <h4>
                            <%= f.label :password_confirmation, class: "form-text" %>
                        </h4>
                        <%= f.password_field :password_confirmation, required: true, id: "user_password_field", class: 'form-control' %>

                        <h4>
                            <%= f.label :username_field, "Username", class: "form-text" %>
                        </h4>
                        <%= f.text_field :username, required: true, id: "user_username_field", class: 'form-control' %>
                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <input type="submit" name="commit" value="Sign Up" class="btn btn-primary btn-lg" data-disable-with="Sign Up">
                    </div>
                    <% end %>
                </div>

            </div>
        </div>
    </div>
</div>

app/views/users/edit.html.erb
<div class="form-container text-center">

    <%= form_for(current_user, url: user_path(current_user), html: { id: "user-edit-form" }) do |f| %>
    <h1 class="text-center">
      Edit User Profile
    </h1>

    <div class="form-group">
       <h4> <%=f.label :image, "Profile Picture", class:'form-text'%> </h4>
      <div id="preview-image">
        <% if current_user.image? %>
          <%= image_tag current_user.image, class: "img-settings img-responsive center-block" %>
        <% end %>
      </div>

      <%= f.file_field :image, id: "user_image_field", class: 'form-control image-uploader' %>

        <h4> <%= f.label :email_field, "Email", class: 'form-text' %> </h4>
        <%= f.text_field :email, required: true, id: "user_email_field", class: 'form-control' %>


        <h4> <%= f.label :password_digest_field, "Password", class: 'form-text' %> </h4>
        <%= f.text_field :password_digest, required: true, id: "user_password_field", class: 'form-control' %>

        <h4> <%= f.label :username_field, "Username", class: 'form-text' %> </h4>
        <%= f.text_field :username, required: true, id: "user_username_field", class: 'form-control' %>
        </div>

        <div class="form-group text-center">
        <%= f.submit "Update Profile", class: "btn btn-success btn-lg" %>
        </div>

    <% end %>
  </div>