config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
   root to: 'landing#index'
   get :about, to: 'static_pages#about'
   post :upvote, to: 'votes#upvote'
   post :downvote, to: 'votes#downvote'
   resources :topics  do
     resources :posts, except: [:show] do
       resources :comments
     end
   end

   resources :users, only: [:new, :edit, :create, :update]
   resources :sessions, only: [:new, :create, :destroy]
   resources :password_resets, only: [:new, :create, :edit, :update]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  extend FriendlyId
  friendly_id :title, :use => :slugged
  mount_uploader :image, ImageUploader

  belongs_to :user
  has_many :comments
  belongs_to :topic
  paginates_per 3

  validates :title, length: {minimum: 3}, presence: true
  validates :body, length: {minimum: 10}, presence: true
  validate :image_size

  before_save :update_slug

  private

  def image_size
    return unless image
    if image.size > 1.megabyte
      errors.add(:image, "size is too big. Please make sure it is 1MB or smaller.")
    end
  end

  def update_slug
    if title
      self.slug = title.gsub(" ", "-")
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  respond_to :js
  before_action :authenticate!, only: [:create, :edit, :update, :new, :destroy]


  def index
    @topic = Topic.includes(:posts).friendly.find(params[:topic_id])
    @posts = @topic.posts.order(created_at: :desc).page params[:page]
    @post = Post.new

  end

  def create
    @topic = Topic.friendly.find(params[:topic_id])
    @post = current_user.posts.build(post_params.merge(topic_id: @topic.id))
    @new_post = Post.new

      if @post.save
        flash.now[:success] = "You've created a new post"
      else
        flash.now[:danger] = @post.errors.full_messages
      end

  end

  def edit
    @post = Post.friendly.find(params[:id])
    @topic = @post.topic
    authorize @post
  end

  def update
    @post = Post.friendly.find(params[:id])
    @topic = @post.topic
    authorize @post

      if @post.update(post_params)
        flash.now[:success] = "Post Updated"
      end
    end

  def destroy
    @post = Post.friendly.find(params[:id])
    @topic = @post.topic
    authorize @post

      if @post.destroy
        flash.now[:danger] = "Post Deleted!"
      end
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :image)
  end

end

app/views/posts/_edit.html.erb
<div class="post-form-update">
  <%= form_for(post, url: topic_post_path(topic, post), remote: true, html: { id: "post-update-form" }) do |f| %>
  <h1 class="text-center">
    Update Post
  </h1>
  <div class="form-group">
    <h4>
      <%=f.label :image, "Post Image", class: 'form-text'%>
    </h4>
    <div id="preview-image">
      <% if @post.image? %>
      <%= image_tag @post.image, class: "img-settings img-responsive center-block" %>
      <% end %>
    </div>
  </div>

  <div class="form-group">
    <%= f.file_field :image, id: "post_image_field", class: 'form-control image-uploader' %>
  </div>

  <div class="form-group">
    <h4>
      <%= f.label :title_field, "Title", class:'form-text' %>
    </h4>
    <%= f.text_field :title, required: true, id: "post_title_field", class: 'form-control' %>
  </div>

  <div class="form-group">
    <h4>
      <%= f.label :text_field, "Body", class:'form-text' %>
    </h4>
    <%= f.text_field :body, id: "post_body_field", class: 'form-control' %>
  </div>

  <div class="form-group text-center">
    <div class="btn btn-success btn-lg cancel-button">
      Cancel
    </div>
    <%= f.submit "Update Post", class: "btn btn-success btn-lg" %>
  </div>

  <% end %>

</div>

app/views/posts/_form.html.erb
<div class="post-form">
  <%= form_for(post, url: topic_posts_path(topic),authenticity_token: true, remote: true, html: { id: "post-create-form", multipart: true }) do |f| %>
    <h1>
      Create Post
    </h1>

    <div class="post-create">
        <h4><%=f.label :image, "Post Image", class: "form-text"%></h4>

          <div id="preview-image">
            <%= image_tag "", class: "input-img" %>
          </div>

          <div class="preview-cancel btn-link">
            Cancel
          </div>

        <%= f.file_field :image, id: "post_image_field", class: 'form-control image-uploader' %>

        <h4> <%= f.label :title_field, "Title",class: "form-text" %> </h4>
        <%= f.text_field :title, required: true, id: "post_title_field", class: 'form-control' %>

        <h4> <%= f.label :text_field, "Body", class: "form-text" %> </h4>
        <%= f.text_field :body, id: "post_body_field", class: 'form-control' %>

        <%= f.submit "Create Post", class: "btn btn-success btn-lg" %>
    </div>
  <%end%>
</div>

app/views/posts/_post.html.erb
<div class="post-child" id="post-form-holder-<%=post.id%>">
  <div class="post-child-container ">
    <div class="post-content column-normal">
      <%=image_tag post.image, class: "post-image"%>
    </div>
    <div class="post-content column-big">
      <div class="post-title text-center">
        <%= link_to post.title, topic_post_comments_path(@topic, post)%>
      </div>
      <div class="post-body">
        <%= post.body %>
      </div>
    </div>
    <div class="post-content column-normal">
      <%=link_to "Posted by #{post.user.username} at #{post.created_at}", root_path %>
        <div class="post-button">
          <%=link_to "Edit", edit_topic_post_path(@topic, post), remote: true, class: 'btn btn-info' %>
          <%=link_to "Delete", topic_post_path(@topic, post),remote: true, method: :delete, data: {Confirm: "Delete?"}, class: 'btn btn-danger'%>
        </div>
    </div>
  </div>
</div>

app/views/posts/create.js.erb
$('#flash-messages-container').html("<%=j render partial: 'partials/flash_messages' %>")

<% if @post.persisted? %>
  $('.post-parent').append("<%=j render partial: 'post', locals: { post: @post, topic: @post.topic } %>")

  $('.post-form-container').html("<%=j render partial: 'posts/form', locals: { post: @new_post, topic: @topic } %>")
<% end %>

app/views/posts/destroy.js.erb
$('#flash-messages-container').html("<%=j render partial: 'partials/flash_messages' %>")

$('#post-form-holder-<%=@post.id%>').remove()

app/views/posts/edit.js.erb
$('#post-form-holder-<%=@post.id%>').html("<%=j render partial: 'edit', locals: {post: @post, topic: @topic} %>")

$('.cancel-button').on('click',function(){
  $('#post-form-holder-<%=@post.id%>').replaceWith("<%=j render partial: 'post', locals: {post: @post, topic: @topic} %>")
})

app/views/posts/index.html.erb
<div class="post-container text-center">

    <h1>Posts</h1>
        <%=link_to "Back to Topics", topics_path, class: 'btn btn-primary' %>

    <div class="post-parent text-center">
        <% @posts.each do |post| %>
        <%= render partial: "post", locals: { post: post, topic: @topic } %>
        <%end%>
    </div>

    <%=paginate @posts%>

    <div class="post-form-container">
        <%= render partial: "form", locals: { post: @post, topic: @topic } %>
    </div>
</div>

app/views/posts/update.js.erb
$('#flash-messages-container').html("<%=j render partial: 'partials/flash_messages' %>")

$('#post-form-holder-<%=@post.id%>').html("<%=j render partial: 'post', locals: { post: @post, topic: @topic } %>")